services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - proxy
      - monitoring

  mariadb:
    image: mariadb:11
    container_name: glpi-mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - internal
      - monitoring

  glpi:
    image: diouxx/glpi:latest
    container_name: glpi
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      TIMEZONE: Europe/Paris
    volumes:
      - glpi_data:/var/www/html
    networks:
      - internal
      - proxy
      - monitoring

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - kuma_data:/app/data
    networks:
      - monitoring

volumes:
  npm_data:
  npm_letsencrypt:
  mariadb_data:
  glpi_data:
  kuma_data:

networks:
  proxy:
    driver: bridge
  internal:
    driver: bridge
  monitoring:
    driver: bridge
