name: CD - Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Go to project and deploy
        run: |
          cd /home/root1/devops_cours
          git fetch origin
          git reset --hard origin/main
          docker compose config -q
          sudo docker compose pull
          sudo docker compose up -d --remove-orphans
