name: CI - Trivy Secret Scan
# Nom du workflow affiché dans GitHub Actions

on:
  push:
    branches:
      - "**"
# Déclenche le workflow sur tous les pushes, peu importe la branche

  pull_request:
# Déclenche aussi le workflow sur chaque pull request

permissions:
  contents: read
# Donne uniquement un accès en lecture au contenu du dépôt
# C’est une bonne pratique de sécurité : on donne le minimum nécessaire

jobs:
  trivy-secret-scan:
    name: Scan repo for secrets
    # Nom lisible du job dans l’interface GitHub Actions

    runs-on: ubuntu-latest
    # Le job s’exécute sur une machine virtuelle Ubuntu fournie par GitHub

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # Récupère le code du dépôt dans le runner
        # Sans cette étape, Trivy ne pourrait pas scanner les fichiers

      - name: Install Trivy
        run: |
          sudo apt-get update
          # Met à jour la liste des paquets disponibles

          sudo apt-get install -y wget gnupg lsb-release
          # Installe les dépendances nécessaires :
          # - wget : pour télécharger la clé et le dépôt
          # - gnupg : pour gérer la clé GPG
          # - lsb-release : pour récupérer la version d’Ubuntu

          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | \
            gpg --dearmor | \
            sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          # Télécharge la clé publique du dépôt Trivy
          # La convertit au format keyring
          # Puis la stocke localement pour vérifier la signature des paquets

          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | \
            sudo tee /etc/apt/sources.list.d/trivy.list
          # Ajoute le dépôt officiel Trivy à la liste des sources APT

          sudo apt-get update
          # Recharge la liste des paquets après ajout du dépôt Trivy

          sudo apt-get install -y trivy
          # Installe Trivy

      - name: Run Trivy secret scan
        run: |
          trivy fs --scanners secret --exit-code 1 .
          # Lance un scan du système de fichiers du dépôt courant
          # --scanners secret : active uniquement la détection de secrets
          # --exit-code 1 : retourne un code d’erreur si un secret est trouvé
          # . = scanne tout le dépôt
